<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Exemplo0002CPUSIMDBench</AssemblyName>
    <RootNamespace>Exemplo0002CPUSIMDBench</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Bionix.ML\Bionix.ML.csproj" />
  </ItemGroup>
</Project>
